services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://192.168.8.209:8002
      - REACT_APP_WOL_SERVICE_URL=http://192.168.8.170:8002
    restart: unless-stopped
    # Uncomment the following lines if you need to mount volumes for development
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public